export enum MessageType {
  SEND_MESSAGE_FROM_AIRSHIP = 1,
  SEND_MESSAGE_FROM_CALBANIA = 2,
  CONFIRM_MESSAGE_FROM_AIRSHIP = 3,
  BROADCAST_TO_CALBANIA_CLIENTS = 4,
  TIMEOUT_MESSAGE_FROM_CALBANIA_CLIENTS = 5
}
